version: "3"

services:
  mock-weather-api:
    build:
      context: ./external/mock-weather-api
      dockerfile: ../mock-weather-api.Dockerfile
    ports:
      - "5000:5000"

  api:
    build:
      context: ./src
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "./src:/code"
    depends_on: 
      - mock-weather-api
    environment:
      DJANGO_SETTINGS_MODULE: "app.settings.dev"
      WEATHER_API_URL: "http://mock-weather-api:5000"
