version: "3"

services:
  mock-weather-api:
    build:
      context: ./external/mock-weather-api
      dockerfile: ../mock-weather-api.Dockerfile
    ports:
      - "5000"

  api:
    build:
      context: ./src
    command: "./run.sh"
    ports:
      - "8000:8000"
    depends_on:
      - mock-weather-api
    environment:
      DJANGO_SETTINGS_MODULE: "app.settings.prod"
      WEATHER_API_URL: "http://mock-weather-api:5000"
